version: '3.1'

services:
  stock-quote-publisher:
    build: ./stock-quote/
    restart: always
    environment:
      RABBITMQ_SERVICE: "rabbitmq"
      RABBITMQ_EXCHANGE: "stocks"
      DURABLE_EXCHANGE: "false"
      PUBLISH_INTERVAL: 5
#      RANDOM_PUBLISH_INTERVAL: 15
#      STOCK_SYMBOLS: "TSLA,INTC,GOOG,MSFT,AMZN,NVDA,NFLX,SBUX,SAP,ADDYY,POAHF,SAP.DE"
  feedback:
    build: ./feedback/
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    environment:
      RABBITMQ_SERVICE: "rabbitmq"
    ports:
      - 18080:18080