name: portfolio

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'portfolio/**'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [11]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Spotless Check
        working-directory: portfolio
        run: mvn spotless:check
      - name: License Check
        working-directory: portfolio
        run: mvn license:check
      - name: Build environment
        run: docker-compose up -d
      - name: Build with Maven
        working-directory: portfolio
        run: mvn -B verify --file pom.xml
