name: stock-quote

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'stock-quote/**'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [11]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Spotless Check
        working-directory: stock-quote
        run: mvn spotless:check
      - name: License Check
        working-directory: stock-quote
        run: mvn license:check
      - name: Build docker setup
        run: docker-compose up -d --build
      - name: Build with Maven
        working-directory: stock-quote
        run: mvn -B package --file pom.xml
